### PR TITLE
Fixes #61 wraps path to start-tc-server.bat in double quotes.

### LINKED ISSUE #61: windows bug.  Invalid characters in file path cause tests to fail
There is a windows bug which was first noticed in ehcache/ehcache3#1217
It is caused by "(" and ")" characters in a folders name.  Although "(" and ")" are valid characters in a folders name, they become a problem when you try run a a command that includes them.  These characters are initially stored in the BasicExternalCluster.displayName instance variable and are eventually used to build a file path, which is then used to invoke a command, which fails.  I believe it is trying to start up the server, and the file path gets truncated at the first occurrence of the "(".

### PR DESCRIPTION
**Pull request by gibsong**
I will check in the ehcache3 integration-test once this is merged.

### CODE REVIEW

**Comment by jd0-sag** [comment]
Revert the whitespace-only changes, first.

**Comment by gibsong** [comment]
ok trying to do that now.  For some reason when I check it out it removes those white spaces automatically.

**Comment by gibsong** [comment]
ok fixed the white spaces.  NetBeans was changing the file on save!  Anyways I pushed the bug fix and a unit test.

**Comment by jd0-sag** [comment]
Yeah, a lot of tools come with the "do random stuff to my source" options enabled, by default, for some reason.  It is one of the reasons why I use a diff tool which isn't part of my IDE (since I don't want them colluding to hide things from me which will pollute the version history and distract other developers).

This change looks good and thanks for including a comment explaining why this case matters (I am one of the people who is pushing for more inline comments in the source so I definitely appreciate it).

We can do a release of these things, tomorrow, if this is causing immediate problems downstream (we can include a non-critical change which went into the passthrough repo, too).  Due to the recent change, only those 2 repos will need the release.

**Pull request merged**
